### ISSUE TITLE
abc.js の実装

### ISSUE THREAD

**Issue by yoshitake266** [yoshitake266/bitComposer_prj#102]
## 動作確認の回
- abc.jsのインストール
- 動作確認

**Comment by yoshitake266** [comment]
アプリの文字列入力のページで楽譜表示させてみたよ
コードはリモートブランチの`yoshitake1107`を見てくれ
jsのフォルダに `abc-basic-min.js` を入れたのと `bcstr.html` の中身を変えた

![abc](https://user-images.githubusercontent.com/43458963/140641180-82df5899-5d83-4c0d-b274-96a00fd9e233.png)

**Comment by yoshitake266** [comment]
- 動的な音の入力
- 音の入力の取り消し

(AIによる)
- 音の長さの入力
- テンポなどの他の入力も入れるか

が僕の心配事

**Comment by Zansan-bit** [comment]
https://paulrosen.github.io/abcjs/overview/example-generator.html
このサイトからデザインと機能の実装できるものがある。
