### ISSUE TITLE
11/8 やったこと

### ISSUE THREAD

**Issue by yoshitake266** [yoshitake266/bitComposer_prj#103]
必ず今日やったこと書いてね。

**Comment by toku-kawasaki** [comment]
ABC.jsで楽譜が現れるように。
しかし、入力と楽譜の記譜法が違うのでどうにかしようと試行錯誤中

**Comment by yoshitake266** [comment]
ABC.js でテキストボックスから文字を入力して楽譜を表示することができた。
しかし、テキストボックスをアクティブにしないと楽譜が表示されないので、動的に表示する方法を模索する
