### ISSUE TITLE
第10スプリント計画

### ISSUE THREAD

**Issue by Zansan-bit** [yoshitake266/bitComposer_prj#106]
AI作曲
 学習させるmidi編集

**Comment by Zansan-bit** [comment]
AIで使用予定のライブラリ TensorFlow,magenta
pythonのバージョンは3.7

**Comment by toku-kawasaki** [comment]
学習させるmidiを作成
smfsepとdominoを使い、midiをメロディだけにする。
今回はpythonを使わない

**Comment by Zansan-bit** [comment]
予定変更　ショパンのものを実装させる

**Comment by Zansan-bit** [comment]
変換順番
midiファイル -(music21)-> 文字ベースの表現 -(連想配列)-> 数値ベースの表現→ tensorflow → 数値ベースの表現 →文字ベースの表現 -(連想配列 → midiファイル -(music21)
