### ISSUE TITLE
今後の計画

### ISSUE THREAD

**Issue by yoshitake266** [yoshitake266/bitComposer_prj#107]
### 最終的に作るもの
  - ゲームの音楽のような曲を作る
    
### やること
  - [オオハタ](https://kenjiohata.hatenablog.com/entry/2018/12/20/000000)のプログラムに長さを入れる
  -  magentaのmelody_rnnを参考にしたコードを上記のプログラムに組み込む
  -  midiのパートの音を合わせるプログラムを作ってその素材を上記のプログラムに組み込む

**Comment by Zansan-bit** [comment]
1.megenta でMelody RNN　探すもの　Lookback , Attention (出来ればMono)

**Comment by Zansan-bit** [comment]
https://qiita.com/83capi/items/c754dfaebb00414aa229
https://qiita.com/tackey/items/860f408e43397f55b160
