### ISSUE TITLE
第2回　プレゼン構成

### ISSUE THREAD

**Issue by Zansan-bit** [yoshitake266/bitComposer_prj#108]
**1. タイトル**
2. 誰でも作曲できるように
3. デモンストレーション
4. 予測から繰り返すことを伝える(判断をAIで)
5. ピアノだと64を和音などにも128もの音を扱う事ができる。
6. 入力から出力までの説明
7.  作曲AIの説明
8. 将来的にするもの
9. 質疑応答

**Comment by yoshitake266** [comment]
プレゼンの担当

発表者: 長島
質疑応答・デモ: 吉川
キーボード写す担当: 野崎

**Comment by Zansan-bit** [comment]
1.bit composerの説明
	自動作曲アプリです
　　ユーザーからWEBキーボードで入力してもらいその続きをAIが作曲してくれます。
2.AIの説明
	音の予測と生成を繰り返すために
	Recursive Neural Network(RNN)を使用してLSTMで学習しています。
3.WEB
	ピアノのGUI
	HTML CSS 
	Javascript　WEB上でピアノの音と楽譜を動かすのに使っています。

**Comment by Zansan-bit** [comment]
反省点
 サーバが落ちた
 作曲のデモは入力するメロディをちゃんと考えたほうがよかった
 発表者用のマイクしか反応しないことに気づかなかった
 mp3のコーディングの問題で長さを入れた作曲のmp3がプレゼンに貼れなかった
