### ISSUE TITLE
プレゼン用issue

### ISSUE THREAD

**Issue by yoshitake266** [yoshitake266/bitComposer_prj#113]
プレゼン用のissue

**Comment by Zansan-bit** [comment]
反省点
1. サーバが落ちた
2. 作曲のデモは入力するメロディをちゃんと考えたほうがよかった
3. 発表者用のマイクしか反応しないことに気づかなかった
4. mp3のコーディングの問題で長さを入れた作曲のmp3がプレゼンに貼れなかった
5. 曲の雰囲気を聞いてもらうようにする。
6. サーバの説明をする。
7. 解決方法などの背景を書く

**Comment by yoshitake266** [comment]
- 発表自体は10分で済ませる

**Comment by Zansan-bit** [comment]
1. 第三回はデモンストレーションは必要?
2. サーバ公開するべきか？(サーバ公開する場合は来賓様限定にするべき)
3. AIの説明はRNNのみか他にするべきか？
4. ファイル構成を入れるか？
5. ゲーム音楽の定義を2-4枚目に入れるべき
6. 苦労した部分や解決を入れる
7. デモンストレーションは録画して再生

**Comment by Zansan-bit** [comment]
プレゼンテーションの資料 
bitComposer_prj/presentation/graduation/bit Composer3 .pptx

**Comment by yoshitake266** [comment]
## 第3回プレゼンのアウトライン
- アプリの名前
- アプリでできること
- アプリのターゲット層
- システム構成図
- 自動作曲システムについて
- Flaskについて
- デモンストレーション
- 今後の課題
  - 苦労したところ
  - アプリの改善点
- 締めの言葉

**Comment by yoshitake266** [comment]
## 第3回プレゼン 改善ver
- 発表の流れ

- プロジェクトのテーマ
  - ゲーム音楽風の曲を作曲
  - 初心者でも簡単に作曲できる

- 作ったもの
  - 自動作曲アプリ bit composer
- アプリでできること
  - ユーザが入力したメロディに続いてゲーム音楽風の曲を作曲

- システム構成図

- 自動作曲システムについて
  - Tensorflowとmusic21を使って自動作曲
  - どのようにしてAIを学習させるか
  - 音を予測、生成する

- WebページのGUIについて
    - 鍵盤を押すと音が鳴り音符が入力される
    - Webピアノと楽譜のプログラム
- デモンストレーション
- 今後の課題
  - アプリの改善点

- 締めの言葉

**Comment by Zansan-bit** [comment]
発表の流れ

**Comment by yoshitake266** [comment]
## 話す言葉

これからbit composerの発表をします。

発表はこのような流れで進行します。
私たちは音楽初心者でも簡単にゲーム音楽風の曲が作れるアプリを開発しました。

自動作曲アプリ bit composerです。

ユーザが作ったメロディに続いてAIが作曲をします。
作った曲をダウンロードすることもできます。

bit composerはこのようなシステムの構成になっています。
サーバを公開しているので、ユーザはURLからアクセスし、
Webページからメロディを入力してサーバに送信します。

入力画面にはピアノがあります。ピアノを弾くと音が入力されて楽譜が表示されます。

自動作曲のプログラムはPythonで実装しました。
AIはRNNで、Tensorflowというライブラリを使っています。
そして、MIDIファイルへの出力にmusic21、mp3などの音声ファイルの出力にはmidi2audioというライブラリを使用しています。

自動作曲のながれはこのようになっております。
まず、ユーザが入力したメロディはabc記法で書かれた文字列としてサーバに送信されます。
そのデータをmusic21で
