### ISSUE TITLE
MIDI→abc記法に変換する方法

### ISSUE THREAD

**Issue by Zansan-bit** [yoshitake266/bitComposer_prj#119]

**Comment by Zansan-bit** [comment]
Python JavaScript で探してみましたが参考資料がなく自力で探すしかない。

**Comment by yoshitake266** [comment]
midiからabc記法に変換して使う機能って何だっけ

**Comment by Zansan-bit** [comment]
そんな機能ありましたけ？ 文字列からmidiにならあった気がします。

**Comment by yoshitake266** [comment]
じゃあissueのタイトルはどんな意味なの？

**Comment by Zansan-bit** [comment]
学習処理されたMIDI(mp3)をabc.jsに楽譜を表示させるのが目的。
この処理の方法とサーバーで処理させるか？ユーザーのPCで処理させるか？
が分からない部分

**Comment by yoshitake266** [comment]
分かった
じゃあabc記法からmusic21で変換した文字列への変換と逆のことすればいいじゃん。サーバ側で

**Comment by Zansan-bit** [comment]
それどこのファイルでしたけ？

**Comment by yoshitake266** [comment]
run.py見ればわかるよ
