### ISSUE TITLE
今後について

### ISSUE THREAD

**Issue by yoshitake266** [yoshitake266/bitComposer_prj#17]
1. どんな作曲AIにするか
2.  マインドマップ
3.  ブログについて

**Comment by toku-kawasaki** [comment]
とりあえず、著作権的な問題は解決したから**ゲームミュージックの作曲AI**とかはどうかな。
**マインドマップ**の件は僕が招待したと思うけど。
**ブログ**は誰が書くか決めなきゃね。

**Comment by yoshitake266** [comment]
著作権の問題は解決したからどんな作曲AIにしようかな 
前回では最初にユーザーにいくつか作曲させてのこりをAIに作ってもらう案が出たけど
どんなイメージを学習にあたえて作曲するのか悩むな

**Comment by yoshitake266** [comment]
とりあえず皆来てからはなそ

**Comment by toku-kawasaki** [comment]
20:30になったら集まってなくても話を進めよう

**Comment by yoshitake266** [comment]
長島来ないね

**Comment by toku-kawasaki** [comment]
もう始めちゃう？

**Comment by yoshitake266** [comment]
見てない状況で勝手に決めるのもな～

**Comment by toku-kawasaki** [comment]
一回slackでメッセージを送ってみるのはどうかな。
それか、明日にするか。

**Comment by yoshitake266** [comment]
30分まで待つ

**Comment by Zansan-bit** [comment]
これで大丈夫かな？

**Comment by yoshitake266** [comment]
大丈夫です

**Comment by yoshitake266** [comment]
今まで話をまとめると
ユーザーの曲の続きをゲームミュージック風にアレンジするってことでいいのかな

**Comment by Zansan-bit** [comment]
PCからissuesに入れるのが1番データ容量を喰うと思う。

**Comment by toku-kawasaki** [comment]
そういう感じ。

**Comment by Zansan-bit** [comment]
ゲームミュージック風が分からない。
オーケストラみたいな感じ？

**Comment by yoshitake266** [comment]
言ってみたけど自分でもよくわからない

**Comment by toku-kawasaki** [comment]
ドラクエ風やゼルダの伝説風、星のカービィ風みたいなことかな

**Comment by Zansan-bit** [comment]
ユーザーの曲て展示中に読み込むのか？
事前に学習させるのか？
どっち？

**Comment by yoshitake266** [comment]
実際にその場で学習させるのには時間がかかるから
事前に学習しておく

**Comment by toku-kawasaki** [comment]
展示中に読み込ませるしかないと思う。
いくつかのサンプルを置いて。

**Comment by Zansan-bit** [comment]
Kawasakiくんのが現実的だね。

**Comment by yoshitake266** [comment]
今考えてみたけどイメージとかを選択とかにしてそれに合わせて曲を作らせるのが自然だけど、ユーザーに楽譜作らせてやるのは想像するのが難しいな

**Comment by toku-kawasaki** [comment]
midiにしろ、楽譜にしろ、かなりの知識が必要だしね。

**Comment by Zansan-bit** [comment]
戦闘BGMとか悲しいシーンで良いと思います。

**Comment by Zansan-bit** [comment]
楽譜だけで奏でるのは無理そう？

**Comment by toku-kawasaki** [comment]
無理そうだと思うけど、やって見る価値はあるね

**Comment by yoshitake266** [comment]
楽譜については学習処理にかかる時間が気になるのよな

**Comment by yoshitake266** [comment]
処理時間が現実的かはわからないけど
その時はその時で考えていけばいいから
いまは目標高めでよさそう

**Comment by yoshitake266** [comment]
DNNのモデル軽量化の手法もあるわけだし

**Comment by Zansan-bit** [comment]
最低基準は楽譜が作れるまでにするべきか。

**Comment by yoshitake266** [comment]
なんだ最低基準て

**Comment by toku-kawasaki** [comment]
とりあえず、
- ゲームミュージック風で行く
- 楽譜を読み込ませる
- 発表やフェスタのときは作ったサンプルを読み込ませる
ということでいいかな。

**Comment by yoshitake266** [comment]
決まりですかね

**Comment by toku-kawasaki** [comment]
次はマインドマップについて。
僕がサイトに招待したと思うけどな。

**Comment by yoshitake266** [comment]
でもゲームミュージック風についてはゲームタイトルにするかファミコン風とかのハードウェアにするか

**Comment by Zansan-bit** [comment]
最低で2月までにどこまで出来ているか？
9月に発表するのでここまで完全させますと明言しなくてはいけないんじゃないかな？

**Comment by Zansan-bit** [comment]
ゲームタイトル風がいいな。

**Comment by toku-kawasaki** [comment]
ゲームタイトルの方がいいと思うよ。
ソッチのほうが作曲者が混ざらないし。

**Comment by yoshitake266** [comment]
まあ、それはとりあえず来週に置いとくか

**Comment by yoshitake266** [comment]
次はマインドマップ担当とブログ担当か

**Comment by yoshitake266** [comment]
マインドマップやりたい人

**Comment by yoshitake266** [comment]
(･∀･)/　ﾊｰｲ

**Comment by Zansan-bit** [comment]
( 'ω')/ ﾊｲ!

**Comment by yoshitake266** [comment]
以上?

**Comment by toku-kawasaki** [comment]
マインドマップは気が向いたときに更新して、
ブログは週替りでいいんじゃない
考えているのは
- 月火 野崎
- 水木  吉川
- 金土 長島
日曜日は休む

**Comment by yoshitake266** [comment]
異論なし

**Comment by Zansan-bit** [comment]
ブログて毎日じゃなかったけ？

**Comment by yoshitake266** [comment]
日曜なくてもいいか相談してみる?

**Comment by Zansan-bit** [comment]
そうしますか。

**Comment by toku-kawasaki** [comment]
じゃあ日曜は誰が書くか決めよう
長島くんはwifiの関係でだめだと思うから
吉川と僕で決めようと思う。

**Comment by toku-kawasaki** [comment]
相談しても絶対門前払いされるに決まっている。
「日曜日暇な人はいないんですか？」って言われるだけだと思う。

**Comment by yoshitake266** [comment]
3人で日報まとめて一人が書く感じかな

**Comment by Zansan-bit** [comment]
4限までなら月曜日も出来そうな気がする。

**Comment by yoshitake266** [comment]
ちなみに僕は土日きついかな

**Comment by Zansan-bit** [comment]
僕は金土日は暇な時が多いから大丈夫です。

**Comment by yoshitake266** [comment]
野崎は土日どうよ

**Comment by toku-kawasaki** [comment]
僕はどっちも大丈夫

**Comment by Zansan-bit** [comment]
平日はPython環境は整っているのでスマホからブログを見ればPCでコード入力してissuesで送れると思います。

**Comment by toku-kawasaki** [comment]
決めた。
- 月火 野崎
- 水木 吉川
- 金土 長島
- 日 野崎と長島
っていうのはどうかな

**Comment by Zansan-bit** [comment]
日曜日は18:00までなら問題はないと思います。

**Comment by yoshitake266** [comment]
どうやって二人で書くのだよ

**Comment by toku-kawasaki** [comment]
日曜は2つ載せようと思う。
6:00-18:00は長島くんが書いて
18:00-22:00は僕が書く

**Comment by Zansan-bit** [comment]
このissuesかslackで会議して内容を決める？

**Comment by yoshitake266** [comment]
書き方って3人の日報をまとめてその日に一人が書く感じで合っているよね

**Comment by toku-kawasaki** [comment]
issueだとメールが多くて困るんだよね。
slackにしよう。
一人が日報をブログにして書くと思うんだけど。

**Comment by yoshitake266** [comment]
じゃあその日一人の日報を書くわけだな

**Comment by toku-kawasaki** [comment]
そうだと思うけど、
休んだときはどうする？

**Comment by yoshitake266** [comment]
じゃあ休んだら吉川が書いて吉川の都合が悪かったら野崎か長島にこちらから頼む

**Comment by toku-kawasaki** [comment]
とりあえず、
- マインドマップは気が向いたときに誰かが書く
- ブログを書く人は曜日ごとに変える
- 休んだら、代わりに他の人が書く

ということでいいかな。

**Comment by yoshitake266** [comment]
いいよ
確認だけど
月火が野崎で
水木が吉川
金土が長島
日曜が野崎と長嶋
これでokね

**Comment by yoshitake266** [comment]
あとガントチャートについてはまた明日相談するけど今決めたほうがいい?

**Comment by toku-kawasaki** [comment]
これでOK

**Comment by Zansan-bit** [comment]
ガントチャートは話し合いで

**Comment by toku-kawasaki** [comment]
`それと、確認だけど[このサイト](https://www.mindmeister.com)に登録した？

**Comment by yoshitake266** [comment]
もしくは２週間の周期にして来週から新しく決めるか

登録したよそっちのマインドマップ見れるよ

**Comment by toku-kawasaki** [comment]
スプリントごとに新しく決めるっていうこと？

**Comment by yoshitake266** [comment]
そうだよ

一応僕のマインドマップも招待しとく?

**Comment by toku-kawasaki** [comment]
招待しておいて。
2週間周期で決めよう。

**Comment by yoshitake266** [comment]
遅くなったがおしまいにしとくか

**Comment by toku-kawasaki** [comment]
そうだね。おしまいにしよう

**Comment by yoshitake266** [comment]
じゃあ. . . バイバイ!
