### ISSUE TITLE
ロゴを作る

### ISSUE THREAD

**Issue by toku-kawasaki** [yoshitake266/bitComposer_prj#18]
ロゴを作りましょう
因みに僕のロゴはこれです
![bit_composerロゴ](https://user-images.githubusercontent.com/84367211/127252155-f99f0692-99dc-488a-b4bd-26a6076b109e.png)

**Comment by Zansan-bit** [comment]
### 僕はこれ[]
![facebook_profile_image](https://user-images.githubusercontent.com/84367201/127252330-46c4c932-c446-464d-ae1c-f15828490ddd.png)

**Comment by yoshitake266** [comment]
吉川の候補
![logo](https://user-images.githubusercontent.com/43458963/127254023-0f1447d2-3f47-4be4-acfe-45ee53ca83df.png)

円はレコードをイメージ

**Comment by Zansan-bit** [comment]
修正版　
![pinterest_board_photo](https://user-images.githubusercontent.com/84367201/127256853-e9d47968-a2fd-4562-a5ae-2861789f92a1.png)

音の反響とnnをイメージして考えました。

**Comment by Zansan-bit** [comment]
> 修正版　
> ![pinterest_board_photo](https://user-images.githubusercontent.com/84367201/127256853-e9d47968-a2fd-4562-a5ae-2861789f92a1.png)
> 
> 音の反響とnnをイメージしてこのデザインにしました。

**Comment by yoshitake266** [comment]
吉川の案はどう思う？

**Comment by toku-kawasaki** [comment]
レコードはいい発想だとは思うけど、レコードは**古いもの**というイメージがあるんだよね。
AIは最新のものというイメージだから

**Comment by yoshitake266** [comment]
もっと電子的なデザインにしたほうがいいか
だとすると野崎の案がいいと思う優しいイメージだし。
フォントに関しては 「Bit Composer」にしたほうがいいかな

**Comment by toku-kawasaki** [comment]
実を言うと長島の案が好きだったりする。
音の反響とNNを模したのは自分では考えられないし。

**Comment by yoshitake266** [comment]
ぱっと見イメージわかるかな長島の案

**Comment by yoshitake266** [comment]
1番イメージがしっくりくるのは野崎の案だな

**Comment by toku-kawasaki** [comment]
まだ長島くんの意見聞けてないから暫定だけど、僕の案でいいね？
修正するまで今から1時間以上かかるけどいい？

**Comment by yoshitake266** [comment]
長島の返信来るまで待とう

**Comment by toku-kawasaki** [comment]
修正しました。
![bit composerロゴ](https://user-images.githubusercontent.com/84367211/127280450-0d1cf5ad-1da8-49c7-8442-4b7549a5e78f.png)

**Comment by Zansan-bit** [comment]
僕の感想としては
野崎さんのが1番わかりやすいけど
シンプル過ぎて印象が薄い。
吉川さんの場合は
レコードぽいのはいいアイデアだと思いますが
クラシック以外だとイメージとは程遠い。
野崎さんのを少し加工すれば良いと思いますので
(仮)としては野崎さんの案が1番良いと思います。

**Comment by yoshitake266** [comment]
じゃあ野崎の案にするってことで
scrapboxに貼ってくれるか

**Comment by toku-kawasaki** [comment]
貼ったよ。

**Comment by yoshitake266** [comment]
ありがとう
