### ISSUE TITLE
開発環境を整える

### ISSUE THREAD

**Issue by toku-kawasaki** [yoshitake266/bitComposer_prj#19]
開発環境を整えましょう
ちなみに僕は
- 教室
    - anaconda3
        - python 3.9.2
    - sublime text3
- 自宅
    - python 3.9.5そのまま
    - visual studio code

必要なパッケージは
- music21
- tensorflow
 
他の人はどうなのか教えてください

**Comment by yoshitake266** [comment]
- 教室
    - anaconda 3 
        - python  ver 3.8.5
        - tensorflow
        - music21
     - sublime text 3
     - git bash

- 自宅
    - anaconda 3
        - python  ver  3.8.5
        - tensorflow
        - music21
     - sublime text 3
     - github desktop

吉川はこんな感じかな

**Comment by Zansan-bit** [comment]
自宅
anaconda 3
　python 3
　tensorflow
　music21
sublime text3
github desktop

**Comment by toku-kawasaki** [comment]
とりあえず、
**pythonのバージョンがバラバラ**なのは
どうにかしないとね

**Comment by yoshitake266** [comment]
自宅と学校でver 3.9.6に統一するか?

**Comment by Zansan-bit** [comment]
学校統一したいな。

2021年8月2日(月) 19:38 yoshitake266 ***@***.***>:

**Comment by toku-kawasaki** [comment]
学校だけでも統一したいよね
3.8.5と3.9.2と3.9.5が同時に存在するってありえないから。

**Comment by Zansan-bit** [comment]
3.9.5が最新バージョンで揃えやすそう。

2021年8月2日(月) 19:42 toku-kawasaki ***@***.***>:

**Comment by toku-kawasaki** [comment]
自宅は3.9.6に統一しようか。
学校は新しい仮想環境を作ってから考えよう。

**Comment by toku-kawasaki** [comment]
そのためにはanacondaをアンインストールして、[pythonをそのまま](https://www.python.org/downloads/windows/)入れなきゃいけないけどね

**Comment by yoshitake266** [comment]
もう一度仮想環境作れってこと?

**Comment by Zansan-bit** [comment]
Pythonのバージョンだけを入力すればいいんじゃないかな？

2021年8月2日(月) 20:20 yoshitake266 ***@***.***>:

**Comment by yoshitake266** [comment]
anaconda で conda install python=3.9.6 でできた

**Comment by toku-kawasaki** [comment]
それでできるならいいよ

**Comment by yoshitake266** [comment]
それじゃあ、自宅のパソコンはOKです。あと学校のを変えるだけ
