### ISSUE TITLE
次に取り組むこと

### ISSUE THREAD

**Issue by yoshitake266** [yoshitake266/bitComposer_prj#20]
スプリント3の予定について

**Comment by Zansan-bit** [comment]
実際にコードを書いて実行したい

**Comment by toku-kawasaki** [comment]
とりあえずデータ採集をしたい。馴染みのあるゲームから何十個のmidiデータを用意したい。

**Comment by yoshitake266** [comment]
ゲームタイトルのmidiを素材にするのはわかっているが、AIでmidiをどう学習するかは把握できてないからメロディーだけを取り出すのか、1音づつ入力にしていくのかをネットなり本なりで探してみようか、サンプルプログラムとかがあると便利。
ひとまずこの2週間はAi学習の準備だね
