### ISSUE TITLE
AI学習のプログラムコードの理解

### ISSUE THREAD

**Issue by yoshitake266** [yoshitake266/bitComposer_prj#22]
[このサイトの説明の中で自分が理解できていることを書いていこう](https://kenjiohata.hatenablog.com/entry/2018/12/20/000000 )
1. プログラムは何を出力するのか
    - (～を作るためのプログラム)
1. プログラムの流れ
    - 上から順に 
    - 大まかな認識でOK  (～をするために～をしている)
1. ライブラリは何に使われているか
    -  (例 LSTM → 入力から曲を予測するのに必要)

**Comment by yoshitake266** [comment]
吉川

1. プログラムは何を出力するのか
    - このプログラムはショパンの曲に似たような曲を出すプログラム

2. プログラムの流れ
    1. ライブラリのインポートをする
    2. ショパンの曲のmidiを入力データにするための前処理
        1.  midiのなかのメロディーのパートを一つ取り出す
        2. パートの中の音を取り出す
        3. パートの中の出てきた音の種類取り出す
        4. 音名を数字と対応付ける
        5. 数字だけにする
    3. 学習データと正解データを作る
        1. 2-5 のlistの先頭から101の音の列を取り出し100までを入力データ101個目を正解データとする
        2. 先頭の位置をずらしながら音を取り出す
        3. 入力データはtensorflowに入れるためにnumpyで100行1列の配列に分ける
        4. 正解データは学習モデルに音の種類分けをさせるため1-hot エンコーディングの形にする
    4. 2,3の流れを複数のファイルに適用
    5. CNNのモデルを作る
    6. 出力結果をmidiに変換

3. ライブラリは何に使われているか
    - music21 → midiからデータを取り出しpythonで扱えるようにする
    - glob → フォルダの中のすべてのmidiを取り出す
    - numpy → tensroflowに使うデータにする
    - np_utils → 正解データを1-hot エンコーディングにする
    - Sequential → モデルの作成
    -  Lambda → 入力の正規化
    - Dense → 全結合層
    - LSTM → 入力から予測した音を求めるための層
    - Dropout → モデルのノードを減らす
    - Activation → 活性化関数
    - Adam → 重みを決めるための関数

長くなってしまったので申し訳ない
皆さんどんな感じですか

**Comment by toku-kawasaki** [comment]
野崎

1. プログラムは何を出力するのか
    - ショパン風のメロディを作成
1. プログラムの流れ
    - tensorflowが読み込める形式にするためにmidiを変換する
    - モデルを構築
    - midiに変換するために数値データをmidiにする
1. ライブラリは何に使われているか
    - music21 → midiを変換したり、数字データをmidiにする
    - glob → ディレクトリにあるmidi全てを読み込む
    - numpy → midiの最初と最後をくっつけないようにしたり、最初の１音を決める
    - np_utils → 1-hot化する
    後は調べないと分からない

これくらいかな。

**Comment by yoshitake266** [comment]
大事なことは
- midiの中のパートと音を取りだす
-  LSTMで学習するための入力データと正解データの作り方
- ニューラルネットワークの組み立て方
- midiとして結果を出力

これらのプログラムが理解できればOKかな

プログラムをまるごと真似して書くわけではないけれど練習がてら何度も書いてみるのもいいかもな

それとこのプログラムだと出力結果の音が均等だから不自然に聞こえてしまう
僕が探した中だと学習の仕方については[このサイトが](https://naotokui.medium.com/deep-learning%E3%82%92%E7%94%A8%E3%81%84%E3%81%9F%E9%9F%B3%E6%A5%BD%E7%94%9F%E6%88%90%E6%89%8B%E6%B3%95%E3%81%AE%E3%81%BE%E3%81%A8%E3%82%81-%E3%82%B5%E3%83%BC%E3%83%99%E3%82%A4-1298d29f8101)参考になるかな

**Comment by Zansan-bit** [comment]
流れとライブラリは分かりました
