### ISSUE TITLE
入れて欲しい作品

### ISSUE THREAD

**Issue by toku-kawasaki** [yoshitake266/bitComposer_prj#24]
今現在

- **8までのドラクエ**
- **スカイウォードソードまでのゼルダの伝説**
- **New スーパーマリオブラザーズ Wiiまでのマリオ**
のmidiをdataブランチに入れました
今後、追加する予定として
- **FF**
- **ソニック・ザ・ヘッジホッグ**
を入れたいと思いますが、他に入れたいゲームシリーズはありますか？
ただし、

- **データが少なすぎるもの**(ピクミンなど)
- **マイナーなゲームシリーズ**
はNGです。

**Comment by yoshitake266** [comment]
マリオ64でお願いします

**Comment by toku-kawasaki** [comment]
ごめん、マリオ64はマリオシリーズに入っているわ。

**Comment by toku-kawasaki** [comment]
ゲームタイトルって書き方が悪かったかな。
ゲームシリーズと書いたほうが良かったかな。

**Comment by Zansan-bit** [comment]
ポケットモンスター　赤緑からXY
艦これ、　東方　、エースコンバット　
どうぶつの森　、星のカービィ

**Comment by yoshitake266** [comment]
複数シリーズあってもいいんじゃないか。ユーザーに画面上で選択させることになりそうだけど

**Comment by toku-kawasaki** [comment]
ポケモン、星のカービィ、どうぶつの森は候補に入れとくよ。
艦これ、東方はmidiが少なすぎる。
エースコンバットはマイナーかな。

10シリーズほど考えているよ。ボタンで決める感じで。

**Comment by Zansan-bit** [comment]
(暇があったら趣味で作ろう)

**Comment by toku-kawasaki** [comment]
個人的に避けたいのは、ほぼ任天堂オンリーになっちゃうこと。
今、候補にあるFF,ドラクエ(スクエニ),ソニック(セガ)以外、任天堂だから。
**留学生でも分かる**ゲームタイトルがいい。

**Comment by Zansan-bit** [comment]
じゃあバイオハザード

**Comment by Zansan-bit** [comment]
ガンダムとか？

**Comment by toku-kawasaki** [comment]
ガンダムはアニメでしょ。
バイオハザードもデータが少ないかな（4以降全く無い)

**Comment by Zansan-bit** [comment]
ガンダムのゲーム出ているよ

**Comment by toku-kawasaki** [comment]
分かってるよ。だけど、ガンダムって言われてゲームは想像しにくいんじゃないかな。

**Comment by Zansan-bit** [comment]
アニメから逆輸入しているか問題ないのでは？

**Comment by toku-kawasaki** [comment]
一応見てみたけど、これもデータが少ない。
今思ったけど、メタルギアソリッドとかはどうかな。
知ってる曲多いし、コナミだし、外国でも小島監督は人気だし。

**Comment by Zansan-bit** [comment]
いいね！

**Comment by Zansan-bit** [comment]
ドラゴンボールとかナルト疾風伝とか

**Comment by toku-kawasaki** [comment]
だからなんで、アニメ原作のゲームしか挙げないの。

**Comment by Zansan-bit** [comment]
難しいな基本アニメからゲームのパターンが多いからFGOとかパズドラ等のスマホゲーが多い

**Comment by Zansan-bit** [comment]
有名だけどアニメ産かゲームだけどマイナーが多い

**Comment by toku-kawasaki** [comment]
後はもうGTAしか浮かばない。今度は留学生は分かるけど、日本人が分かるか微妙だし。
吉川くんにも意見を聞こう。

**Comment by Zansan-bit** [comment]
モンハン

**Comment by toku-kawasaki** [comment]
モンハンはデータがなかった。
メタルギアソリッドもデータがちょっと少ない（けどお試しとして入れている）。
今考えているのは

- 任天堂タイトル5作品
- その他タイトル5作品

**Comment by toku-kawasaki** [comment]
とりあえず
任天堂枠は

- マリオ
- ポケモン
- ゼルダの伝説

あと2枠。

その他枠は

- メタルギアソリッド
- ソニック
- ドラゴンクエスト
- ファイナルファンタジー

あと1枠。

とりあえず知ってるゲームシリーズを挙げて（マイナーなやつ、データが少なすぎるやつはNG）

**Comment by yoshitake266** [comment]
motherお願い

**Comment by toku-kawasaki** [comment]
mother、星のカービィを入れたので、後はその他枠１つ。

**Comment by toku-kawasaki** [comment]
ストリートファイターを入れたので最終的に
任天堂枠は
- マリオ
- ゼルダの伝説
- 星のカービィ
- mother
- ポケモン

その他枠は

- ドラゴンクエスト
- ファイナルファンタジー
- ソニック
- メタルギアソリッド
- ストリートファイター

になりました。
