### ISSUE TITLE
夏休みに何をするか

### ISSUE THREAD

**Issue by toku-kawasaki** [yoshitake266/bitComposer_prj#36]
# 三週間の夏休みに何をするか考えましょう。

僕はコードのデバッグをしたいです

**Comment by Zansan-bit** [comment]
核となる作曲アルゴリズムの作成。

**Comment by toku-kawasaki** [comment]
分かった。吉川くんを待とう。

**Comment by yoshitake266** [comment]
学習モデル作るのとシステムの構成を考える。だな
まあ、学習モデルは作ってもいろいろ試して改良していくことになりそうだな

**Comment by toku-kawasaki** [comment]
つまり

- 長島 作曲アルゴリズムの作成
- 吉川 学習モデル作成とシステム構成
- 野崎 コードのデバッグ
ということになるんだけど、「作曲アルゴリズムの作成」と「学習モデル作成」の違いが分らないんだけど。
あと、システム構成は皆で考えようよ。

**Comment by Zansan-bit** [comment]
学習モデルの作成でいいよ。
だた候補を探している最中です。

**Comment by yoshitake266** [comment]
とりあえずシステムの案は考えたほうがいいだろう。

**Comment by toku-kawasaki** [comment]
分かった

- 長島 学習モデルの作成とシステム構成
- 吉川 学習モデルの作成とシステム構成
- 野崎 学習モデルのコードのデバッグとシステム構成

僕のパソコンはスペックがそんなにないので、コードが動くかどうかだけで実際に実行するのは違う人がいいな。

**Comment by Zansan-bit** [comment]
学習モデルのシステム構築はどうするかが重要ですね？

**Comment by toku-kawasaki** [comment]
「システム構成」ってシステム構成図のことだと思うんだけど。

**Comment by yoshitake266** [comment]
うん。構成ができたら図描く

**Comment by toku-kawasaki** [comment]
システム構成のissueも作ったほうがいい？

**Comment by yoshitake266** [comment]
webシステムの流れについてっていうissueがあるからそれ使う

**Comment by toku-kawasaki** [comment]
分かった。
最終的に
 - 長島 学習モデルの作成とシステム構成を考える
 - 吉川 学習モデルの作成とシステム構成を考える
 - 野崎 学習モデルのデバッグとシステム構成を考える

システム構成図を書くのは誰がいい？
