### ISSUE TITLE
今日の振り返り

### ISSUE THREAD

**Issue by yoshitake266** [yoshitake266/bitComposer_prj#37]
今日の振り返りをしよう

**Comment by yoshitake266** [comment]
midiの学習のさせ方を決めるためにmidiのMessageについて学習したよ

**Comment by toku-kawasaki** [comment]
Flaskを動かしてみた。
webアプリでも書くけど、Flaskは書くのがすごく簡単
明日はDjangoを動かしてみようと思う。
