### ISSUE TITLE
FlaskとDjango、どっちがいいか

### ISSUE THREAD

**Issue by toku-kawasaki** [yoshitake266/bitComposer_prj#39]
FlaskかDjangoのどっちがいいか決めましょう。
全員がチュートリアルを終わらせたら、開始

**Comment by yoshitake266** [comment]
Djangoはこれか
https://docs.djangoproject.com/ja/3.2/intro/tutorial01/

**Comment by toku-kawasaki** [comment]
これだよ。
因みにFlaskは[これ](https://flask.palletsprojects.com/en/2.0.x/tutorial/index.html)

**Comment by yoshitake266** [comment]
とりあえずHTMLの表示ぐらいは両方とも試したよ
今のところ両方全然違うことは見当たらなかった
強いて言うならファイル構成とかはdjangoの方が複雑だったからflaskのほうが楽に使えたことくらいかな

**Comment by yoshitake266** [comment]
データベースも使い方調べたほうがいいか？
今のところ使う予定なさそうだけど

**Comment by toku-kawasaki** [comment]
ログインとかしないから調べなくて大丈夫。
実を言うとhtmlの書き方は少し違うけどね。
まぁ長島くんを待って決めよう。

**Comment by Zansan-bit** [comment]
Django は終わったけど
Fjagoはまだ

**Comment by toku-kawasaki** [comment]
Flaskね。
長島くんがFlaskのチュートリアルを終わらせたらこの話を続けよう。

**Comment by yoshitake266** [comment]
書き方違うだけなら厳密にどっちが便利か決める必要はないと思うけどな。

**Comment by toku-kawasaki** [comment]
長島くんがFlaskのチュートリアルを終わらせたらまた決めるけど
今のところはファイル構成が簡単なFlaskでいいかな。

**Comment by yoshitake266** [comment]
ちょいちょいチュートリアル進めるか

**Comment by Zansan-bit** [comment]
Flask のほうが書きやすい

**Comment by yoshitake266** [comment]
じゃあ皆flaskでいいね

**Comment by toku-kawasaki** [comment]
じゃあFlaskにしようか。

**Comment by toku-kawasaki** [comment]
とりあえずhtmlとcssはtoku_02ブランチに入れているから、二人は用意しなくていいよ。
