### ISSUE TITLE
具体的な成果物と土・日・来週何するか

### ISSUE THREAD

**Issue by yoshitake266** [yoshitake266/bitComposer_prj#4]
# TOPIC
- どんな曲を作るAIなのかを決めよう
- 今から１週間の目標

**Comment by yoshitake266** [comment]
### wikiに書いてある案
- 既存の曲のメロディーを学習して曲調の似た曲を作る
- 四季などの言葉からそのイメージに沿った曲を作る
- その場で数秒間の曲を作る

なんかほかにある?

**Comment by toku-kawasaki** [comment]
最初だけ作曲してもらい、後の部分はAIが自動的に作曲する

というのはどう?

**Comment by Zansan-bit** [comment]
クラシックのほうが著作権的な理由でいいと思います

**Comment by yoshitake266** [comment]
初めはユーザーに作曲させるのか？

**Comment by toku-kawasaki** [comment]
クラシックは著作権的なことではいいけど、他の人が理解できるのかわからないのが問題だと思う

ユーザーに作曲といっても簡単なシーケンサーだけどね

**Comment by yoshitake266** [comment]
既存の曲使うんだったらクラシックだな
ゲームミュージックとかだと確か個人利用以外はできなかったと思う

**Comment by yoshitake266** [comment]
シーケンサーってなんすか？

**Comment by Zansan-bit** [comment]
ユーザーが作曲するにはMIDIキーボードかプログラミングで書かないと無理なのでは？

**Comment by toku-kawasaki** [comment]
シーケンサーって[こういうもの](https://info.shimamura.co.jp/digital/newitem/2018/12/128102)。
プログラミングでシーケンサーを作るしかないと思う

**Comment by yoshitake266** [comment]
なんかスイッチ押して入力させるのか

**Comment by yoshitake266** [comment]
どう使うの[これ](https://info.shimamura.co.jp/digital/newitem/2018/12/128102)

**Comment by toku-kawasaki** [comment]
使うんじゃなくてそれに似たインターフェイスを作るっていうだけ
使ったことがないからわからないけど、押した所が光ってmidiにつながった機器から音がなるんだと思う

**Comment by yoshitake266** [comment]
要は画面上でキーボード作って鳴らすのか？

**Comment by toku-kawasaki** [comment]
そういうこと。

**Comment by yoshitake266** [comment]
インターフェース作るんだったらmusic21とかと連携させて楽譜作ってあとは自動的に作らすのはどうだ

**Comment by yoshitake266** [comment]
何小節か書いてあとは自動的に作らせる

**Comment by toku-kawasaki** [comment]
それはいいね。
楽譜を作って自動的に作曲するって言うのも一つの手だね

**Comment by toku-kawasaki** [comment]
とりあえず、クラシックを作曲するAIでいいの？

**Comment by yoshitake266** [comment]
既存の曲を学習させて曲を作らせることを題材にするならそうだね

**Comment by yoshitake266** [comment]
何小節か書いたやつをある作曲者と似たような曲に仕上げるとかだと必要かな

**Comment by yoshitake266** [comment]
まあクラシック曲学習させることにしよう

**Comment by yoshitake266** [comment]
単にクラシックを作曲させるAIではダメだな
何小節か書いたものをその作曲者の特徴に合わせて自動作曲するAIとか

**Comment by yoshitake266** [comment]
これでいい？

**Comment by toku-kawasaki** [comment]
クラシック曲の問題は、誰がどんな雰囲気と分かるのかがあまりいないんだよね。
ショパン風とかベートーベン風とか言われてもどんな雰囲気か分からないでしょ。

**Comment by yoshitake266** [comment]
ゲームミュージック学習して64風とかファミコン風とかできたらいいんだけどな〜

**Comment by toku-kawasaki** [comment]
- ゲームミュージックはわかりやすいけど、著作権的な問題がある
- クラシックは著作権的な問題はないけど、分かりづらい

分かりやすくて、著作権的な問題はない素材があればいいんだけどね。

**Comment by yoshitake266** [comment]
学習とかに使っちゃダメなの？

**Comment by toku-kawasaki** [comment]
僕の貼ったサイトだと「売っちゃだめ、娯楽に使って」と書いているけど、売らない卒業制作程度なら大丈夫だと思うけど、どこまでが娯楽なのかは不明なんだよね。

**Comment by toku-kawasaki** [comment]
[これ](https://www.vgmusic.com/information/legal.php)を見て翻訳した結果だけど。

**Comment by yoshitake266** [comment]
そこんとこ、ちょっと先生に相談してみるか

**Comment by toku-kawasaki** [comment]
それがいいと思う。
多分、いいとは思うけど。
後は、著作権フリーの普通の音楽とかはどうかな？
普通の音楽でも明るいとか暗いとか決めれると思うよ

一週間の目標は長島くんがお風呂から戻ってから決めよう。

**Comment by yoshitake266** [comment]
とりあえずまだ決まらないな
課題として
- 学習するのに良いクラシック作曲者
- 曲の著作権問題
- midi以外にmp3などを使って学習できないか
これらを中心に再来週までに解決しよう

**Comment by toku-kawasaki** [comment]
次は、一週間の目標かな。
総合して一番時間を使えるのは僕だと思う。
