### ISSUE TITLE
これからやること

### ISSUE THREAD

**Issue by yoshitake266** [yoshitake266/bitComposer_prj#41]
第5スプリントの計画を立てる

**Comment by yoshitake266** [comment]
10月にプレゼンがあるのでそれまでには
- システム構成の確認
- 入力画面のwebページを改良する
- プレゼン資料の作成
これらを進めていきたい

**Comment by toku-kawasaki** [comment]
僕は
- webページのデザイン
- 入力画面の改良
- プレゼン資料作成
- Flaskのコードを書く
ことをやりたいかな

**Comment by Zansan-bit** [comment]
僕はプレゼンの資料作成でもやろうかな？

**Comment by toku-kawasaki** [comment]
とりあえず、
 - 吉川 システム構成の確認、webページのデザイン、プレゼン資料作成
 - 野崎 webページのデザイン、プレゼン資料作成
 - 長島 プレゼン資料作成

ってことでいいのかな?

**Comment by yoshitake266** [comment]
10月までにはwebページのデモプレイをプレゼンでやってみたいから、みんなでwebページの構成だのデザインだのを考えていきたい

**Comment by toku-kawasaki** [comment]
じゃあ、

 - 吉川 システム構成の確認、webページのデザインと構成、プレゼン資料作成
 - 野崎 webページのデザインと構成、プレゼン資料作成
 - 長島 webページのデザインと構成、プレゼン資料作成

でいいかな？

**Comment by yoshitake266** [comment]
いいよ

**Comment by toku-kawasaki** [comment]
じゃあcloseする？

**Comment by Zansan-bit** [comment]
学習モデルがまだ決まっていないのが気掛かりではある

**Comment by toku-kawasaki** [comment]
それはwebページの構成とデザインが終わったら考えよう。
一回忘れたほうがアイデアは出やすいって先生が言っていたから。

**Comment by yoshitake266** [comment]
LSTM使って作曲することはわかっているけどね。ゲームタイトルの曲風にアレンジして自動作曲してくれるって説明だけでもいいと思うけどな

**Comment by Zansan-bit** [comment]
まだ再テストしないといけないのと来週テストだから動けるかわからないが

**Comment by toku-kawasaki** [comment]
じゃあcloseするよ。
