### ISSUE TITLE
今日の相談

### ISSUE THREAD

**Issue by yoshitake266** [yoshitake266/bitComposer_prj#45]
第5スプリントに関する確認

**Comment by yoshitake266** [comment]
学習モデル云々は置いといてwebページを改良していかなきゃな

**Comment by Zansan-bit** [comment]
webサーバーをどこにするか目星を付けていますか？

**Comment by yoshitake266** [comment]
つけてないからそこも考えなきゃな
とっさに思いつくのはtomcatとかかな

**Comment by Zansan-bit** [comment]
Webサーバは正直わからないから何とも言えません

**Comment by toku-kawasaki** [comment]
WebサーバはApacheがいいってQiitaに書いてあったけど、設定が必要らしい。

**Comment by yoshitake266** [comment]
まだ開発段階だから実装する際のwebサーバは考えなくていいかな。先生も言っていたけど
開発だったらflaskにあるwebサーバでいいか。

**Comment by Zansan-bit** [comment]
先生も言っていたのでまだ先でもいいと思います
