### ISSUE TITLE
webページをどうするか

### ISSUE THREAD

**Issue by toku-kawasaki** [yoshitake266/bitComposer_prj#50]
**このまま**にするか、それとも**かなり凝ったもの**にするか。
今のままだと、目がかなり痛い。
かなり凝ったものにしたいなら、クレジットとか入れたい。

**Comment by yoshitake266** [comment]
margeしてあるか?

**Comment by toku-kawasaki** [comment]
margeしてあるよ。

**Comment by yoshitake266** [comment]
Webサーバは何できどうすればいいんだ? コマンドプロンプト?

**Comment by toku-kawasaki** [comment]
run.pyを実行すればいいだけだけど
