### ISSUE TITLE
システム要件

### ISSUE THREAD

**Issue by yoshitake266** [yoshitake266/bitComposer_prj#71]
わかるようにすること
- 入力したものを送信する形式: json?
- 曲を出力する形式: mp3?
- AIに入力する形式: midi
- それらを変換するプログラム
- 入力する情報

いい感じの形式あったら共有しよう

**Comment by Zansan-bit** [comment]
変換順番

文字列　→ midiファイル -(music21)-> 文字ベースの表現 -(連想配列)-> 数値ベースの表現→ tensorflow → 数値ベースの表現 →文字ベースの表現 -(連想配列 )→ midiファイル -(music21)→MP3
