### ISSUE TITLE
キーボードのボタン配置

### ISSUE THREAD

**Issue by Zansan-bit** [yoshitake266/bitComposer_prj#76]
今のままだと使いずらいのでいいキー配列があれば書き込んでください

**Comment by toku-kawasaki** [comment]
それともこんな感じはどうかな？
![image](https://user-images.githubusercontent.com/84367211/137691268-9d19793d-5f8f-4c4b-8022-bc10fcb4a4e0.jpeg)

これもいい配列だと思う。
